// Generated by the CLI (regenerateGeneratedFiles) from whichever private-page
// slugs are actually installed — see privateNavItemsFor()/VITE_ROUTES in
// src/lib/managed-files.ts. Do not hand-edit; this placeholder is overwritten
// on every `design-kit init`/`update`/`remove`.
export const PRIVATE_NAV_ITEMS: { label: string; href: string }[] = [
  { label: 'Chat', href: '/chat' },
  { label: 'Account', href: '/dashboard' },
]
